site_name: Gorgoglio
site_url: https://gorgoglio.it/docs/
docs_dir: content

nav:
  - Home: index.md
  - Introduzione:
    - Cos'è Gorgoglìo: intro/gorgoglio.md
    - Cos'è l'idroponica: intro/hydroponic.md
    # - Tipi di sistemi idroponici: intro/systems.md
    - FAQ sull'idroponica: intro/faq.md
  - Soluzioni:
    - Panoramica delle soluzioni: solutions/overview.md
    - Orto in cassetta:
      - Panoramica: solutions/orto_in_cassetta/overview.md
      - Componenti: solutions/orto_in_cassetta/components.md
      - Costruzione: solutions/orto_in_cassetta/build.md
      - Coltivazione: solutions/orto_in_cassetta/cultivation.md
    # - Smart Kratky:
    #   - Panoramica: solutions/smartkratky/overview.md
    # - NFT:
    #   - Panoramica: solutions/nft/overview.md
    #   - Costruzione:
    #     - Meccanica:
    #       - Componenti: solutions/nft/mechanical/components.md
    #       - Struttura della serra: solutions/nft/mechanical/structure.md
    #     - Impianto idraulico:
    #       - Componenti impianto idraulico: solutions/nft/plumbing/components.md
    #       - Schema impianto idraulico: solutions/nft/plumbing/layout.md
    #       - Assemblaggio impianto idraulico: solutions/nft/plumbing/assembly.md
    #     - Impianto elettrico:
    #       - Componenti impianto elettrico: solutions/nft/electrical/components.md
    #       - Schema elettrico: solutions/nft/electrical/wiring.md
    #       - Cablaggio impianto elettrico: solutions/nft/electrical/assembly.md
    #     - Software:
    #       - Panoramica del software: solutions/nft/overview.md
    #       - Installazione e configurazione: solutions/nft/setup.md
    #       - Utilizzo del software: solutions/nft/usage.md
    #   - Coltivazione:
    #     - Nutrienti e soluzioni: solutions/nft/cultivation/nutrients.md
    #     - Piante adatte all'idroponica: solutions/nft/cultivation/plants.md
    #     - Parametri ambientali: solutions/nft/cultivation/environment.md
    #     - Risoluzione dei problemi: solutions/nft/cultivation/troubleshooting.md
  - Contribuisci: contribute.md
  - Licenza: license.md


theme:
  name: material
  palette:
    # Colori principali
    primary: 'green'   # Verde (Primario)
    accent:  'orange'   # Blu (Secondario)

  icon:
    logo: material/sprout 

  # Font
  font:
    text: Roboto
    code: monospace # Font predefinito per il codice va bene di solito

  # Funzionalità aggiuntive (alcune sono abilitate di default)
  features:
    - search # Abilita la ricerca
    - content.code.copy # Aggiunge un pulsante per copiare il codice


extra_css:
  - assets/css/cards.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption