name: Build and Deploy Hugo + MkDocs

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
        with:
          submodules: true  # necessario per i temi Hugo come submodules

      # Setup Python for MkDocs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Setup Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.1'
          extended: true

      # Build Hugo site from /site to /public
      - name: Build Hugo site
        working-directory: site
        run: hugo --destination ../public

      # Build MkDocs site to ./public/docs
      - name: Build the documentation
        working-directory: docs
        run: mkdocs build --site-dir ../public/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
